"""GitHub Pages branch delivery."""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from aurora.config import GitHubPagesDeliveryConfig
from aurora.models import DeliveryResult, RenderedDigest
from aurora.pipeline import StageContext


SITE_TITLE = "Aurora"
SITE_DESCRIPTION = "Personal intelligence digest for research, repositories, and technology news."
SITE_URL = "https://kenny2077.github.io"
SITE_BASEURL = "/Aurora"

MODE_LABELS = {
    "unified_digest": "Unified Digest",
    "scholar": "Scholar",
    "repo_learning": "Repo Learning",
    "tech_news": "Tech News",
}


def write_pages_artifact(
    rendered: RenderedDigest,
    context: StageContext,
    config: GitHubPagesDeliveryConfig,
) -> DeliveryResult:
    """Write a Jekyll-ready GitHub Pages site for one digest."""
    site_dir = config.publish_dir
    site_dir.mkdir(parents=True, exist_ok=True)
    _write_site_scaffold(site_dir)

    digest_time = _site_datetime(context)
    post_path = _write_digest_post(site_dir, rendered, context, digest_time)
    latest_path = _write_latest_mode_page(site_dir, rendered, context, digest_time)
    return DeliveryResult(
        channel="github_pages",
        destination=str(post_path),
        metadata={
            "site_dir": str(site_dir),
            "post_path": str(post_path),
            "latest_path": str(latest_path),
            "index_path": str(site_dir / "index.md"),
            "feed_path": str(site_dir / "feed.xml"),
        },
    )


def _write_site_scaffold(site_dir: Path) -> None:
    (site_dir / "_posts").mkdir(parents=True, exist_ok=True)
    (site_dir / "_includes").mkdir(parents=True, exist_ok=True)
    (site_dir / "assets" / "css").mkdir(parents=True, exist_ok=True)
    (site_dir / "_config.yml").write_text(_config_yml(), encoding="utf-8")
    (site_dir / "index.md").write_text(_index_markdown(), encoding="utf-8")
    (site_dir / "feed.xml").write_text(_feed_xml(), encoding="utf-8")
    (site_dir / "_includes" / "head-custom.html").write_text(
        _head_custom_html(), encoding="utf-8"
    )
    (site_dir / "assets" / "css" / "aurora.css").write_text(_aurora_css(), encoding="utf-8")
    for mode in MODE_LABELS:
        _write_mode_index_placeholder(site_dir, mode)


def _write_digest_post(
    site_dir: Path,
    rendered: RenderedDigest,
    context: StageContext,
    digest_time: datetime,
) -> Path:
    post_slug = _post_slug(rendered.mode)
    post_path = site_dir / "_posts" / f"{digest_time:%Y-%m-%d}-{post_slug}.md"
    item_counts = _item_counts(rendered)
    item_count = _item_count(rendered, item_counts)
    front_matter = _front_matter(
        {
            "layout": "default",
            "title": rendered.title,
            "date": digest_time.strftime("%Y-%m-%d %H:%M:%S %z"),
            "mode": rendered.mode,
            "run_id": context.run_id,
            "item_count": item_count,
            "item_counts": item_counts,
            "permalink": f"/archive/{digest_time:%Y-%m-%d}-{post_slug}/",
        }
    )
    post_path.write_text(
        f"{front_matter}\n\n{rendered.markdown.rstrip()}\n\n---\n\n"
        f"Generated by Aurora from run `{context.run_id}`.\n",
        encoding="utf-8",
    )
    return post_path


def _write_latest_mode_page(
    site_dir: Path,
    rendered: RenderedDigest,
    context: StageContext,
    digest_time: datetime,
) -> Path:
    mode_dir = site_dir / rendered.mode
    mode_dir.mkdir(parents=True, exist_ok=True)
    markdown_path = mode_dir / "index.md"
    post_slug = _post_slug(rendered.mode)
    front_matter = _front_matter(
        {
            "layout": "default",
            "title": f"Latest {MODE_LABELS.get(rendered.mode, rendered.mode)}",
            "permalink": f"/{rendered.mode}/",
            "mode": rendered.mode,
            "run_id": context.run_id,
            "date": digest_time.strftime("%Y-%m-%d %H:%M:%S %z"),
        }
    )
    archive_link = f"/archive/{digest_time:%Y-%m-%d}-{post_slug}/"
    markdown_path.write_text(
        f"{front_matter}\n\n"
        f'<p class="aurora-back"><a href="{{{{ {json.dumps(archive_link)} | relative_url }}}}">'
        "Archive permalink</a></p>\n\n"
        f"{rendered.markdown.rstrip()}\n",
        encoding="utf-8",
    )
    return markdown_path


def _write_mode_index_placeholder(site_dir: Path, mode: str) -> Path:
    mode_dir = site_dir / mode
    mode_dir.mkdir(parents=True, exist_ok=True)
    markdown_path = mode_dir / "index.md"
    label = MODE_LABELS.get(mode, mode)
    front_matter = _front_matter(
        {
            "layout": "default",
            "title": f"Latest {label}",
            "permalink": f"/{mode}/",
            "mode": mode,
        }
    )
    markdown_path.write_text(
        f"{front_matter}\n\n"
        f"# Latest {label}\n\n"
        f"No dedicated {label} digest has been published yet.\n\n"
        "Open the [latest unified digest]({{ '/unified_digest/' | relative_url }}) "
        "for current Aurora output.\n",
        encoding="utf-8",
    )
    return markdown_path


def _config_yml() -> str:
    return "\n".join(
        [
            f"title: {_yaml_scalar(SITE_TITLE)}",
            f"description: {_yaml_scalar(SITE_DESCRIPTION)}",
            f"url: {_yaml_scalar(SITE_URL)}",
            f"baseurl: {_yaml_scalar(SITE_BASEURL)}",
            "theme: jekyll-theme-cayman",
            "markdown: kramdown",
            "permalink: /archive/:year/:month/:day/:title/",
            "defaults:",
            "  - scope:",
            "      path: \"\"",
            "    values:",
            "      layout: default",
            "",
        ]
    )


def _index_markdown() -> str:
    return """---
layout: default
title: Aurora
---

# Aurora

Aurora publishes a personal intelligence digest across research papers, GitHub repositories, and timely technology news.

<nav class="aurora-mode-nav">
  <a href="{{ '/unified_digest/' | relative_url }}">Unified Digest</a>
  <a href="{{ '/scholar/' | relative_url }}">Scholar</a>
  <a href="{{ '/repo_learning/' | relative_url }}">Repo Learning</a>
  <a href="{{ '/tech_news/' | relative_url }}">Tech News</a>
  <a href="{{ '/feed.xml' | relative_url }}">RSS</a>
</nav>

## Latest Digest Pages

- [Unified Digest]({{ '/unified_digest/' | relative_url }})
- [Scholar]({{ '/scholar/' | relative_url }})
- [Repo Learning]({{ '/repo_learning/' | relative_url }})
- [Tech News]({{ '/tech_news/' | relative_url }})

## Latest Published Digest

{% assign latest = site.posts.first %}
{% if latest %}
<article class="aurora-latest-digest">
  <p class="aurora-meta">{{ latest.date | date: "%Y-%m-%d %H:%M" }} <span class="aurora-pill">{{ latest.mode }}</span></p>
  {{ latest.content }}
</article>
{% else %}
No digest posts have been published yet.
{% endif %}

## Archive

{% if site.posts.size > 0 %}
{% for post in site.posts limit: 30 %}
- [{{ post.title }}]({{ post.url | relative_url }}) <span class="aurora-pill">{{ post.mode }}</span> {{ post.date | date: "%Y-%m-%d" }}
{% endfor %}
{% else %}
No digest posts have been published yet.
{% endif %}
"""


def _feed_xml() -> str:
    return """---
layout: null
---
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>{{ site.title | xml_escape }}</title>
    <link>{{ site.url }}{{ site.baseurl }}/</link>
    <description>{{ site.description | xml_escape }}</description>
    {% for post in site.posts limit: 30 %}
    <item>
      <title>{{ post.title | xml_escape }}</title>
      <link>{{ site.url }}{{ site.baseurl }}{{ post.url }}</link>
      <guid>{{ site.url }}{{ site.baseurl }}{{ post.url }}</guid>
      <pubDate>{{ post.date | date_to_rfc822 }}</pubDate>
      <description>{{ post.excerpt | strip_html | strip_newlines | xml_escape }}</description>
    </item>
    {% endfor %}
  </channel>
</rss>
"""


def _head_custom_html() -> str:
    return '<link rel="stylesheet" href="{{ \'/assets/css/aurora.css\' | relative_url }}">\n'


def _aurora_css() -> str:
    return """body {
  color: #1c2430;
}

.page-header {
  background-color: #12355b;
  background-image: linear-gradient(120deg, #12355b, #3d7a89);
}

.main-content {
  max-width: 980px;
}

.main-content h1,
.main-content h2,
.main-content h3 {
  color: #12355b;
}

.aurora-mode-nav {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin: 1.25rem 0 2rem;
}

.aurora-mode-nav a,
.aurora-pill {
  border: 1px solid #c7d5df;
  border-radius: 6px;
  color: #12355b;
  display: inline-block;
  font-size: 0.85rem;
  line-height: 1.2;
  padding: 0.35rem 0.55rem;
  text-decoration: none;
}

.aurora-mode-nav a:hover {
  background: #eef6f8;
}

.aurora-pill {
  background: #eef6f8;
  margin-left: 0.35rem;
}

.aurora-back {
  margin: 1rem 0 1.5rem;
}

.aurora-latest-digest {
  border-top: 1px solid #d6e1e7;
  margin: 1.25rem 0 2rem;
  padding-top: 0.5rem;
}

.aurora-meta {
  color: #637083;
  font-size: 0.9rem;
}

.main-content li {
  margin: 0.35rem 0;
}
"""


def _front_matter(fields: dict[str, object]) -> str:
    lines = ["---"]
    for key, value in fields.items():
        if isinstance(value, dict):
            if not value:
                lines.append(f"{key}: {{}}")
                continue
            lines.append(f"{key}:")
            for child_key, child_value in sorted(value.items()):
                lines.append(f"  {child_key}: {_yaml_scalar(child_value)}")
            continue
        lines.append(f"{key}: {_yaml_scalar(value)}")
    lines.append("---")
    return "\n".join(lines)


def _yaml_scalar(value: object) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int | float):
        return str(value)
    return json.dumps(str(value))


def _site_datetime(context: StageContext) -> datetime:
    value = context.until or context.started_at
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    timezone_name = context.config.run.timezone if context.config is not None else "Asia/Shanghai"
    try:
        target_timezone = ZoneInfo(timezone_name)
    except ZoneInfoNotFoundError:
        target_timezone = timezone.utc
    return value.astimezone(target_timezone)


def _post_slug(mode: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", mode.lower()).strip("-") or "digest"


def _item_counts(rendered: RenderedDigest) -> dict[str, int]:
    value = rendered.metadata.get("item_counts")
    if not isinstance(value, dict):
        return {}
    counts: dict[str, int] = {}
    for key, count in value.items():
        if not isinstance(key, str) or not key.strip():
            continue
        try:
            counts[key.strip()] = max(0, int(count))
        except (TypeError, ValueError):
            continue
    return counts


def _item_count(rendered: RenderedDigest, item_counts: dict[str, int]) -> int:
    if item_counts:
        return sum(item_counts.values())
    for key in ("selected_item_ids", "recommended_repo_ids"):
        value = rendered.metadata.get(key)
        if isinstance(value, list):
            return len(value)
    match = re.search(r"Selected\s+(\d+)\s+", rendered.markdown)
    if match:
        return int(match.group(1))
    return 0
