from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from aurora.config import AuroraConfig, GitHubPagesDeliveryConfig
from aurora.delivery.github_pages import write_pages_artifact
from aurora.models import RenderedDigest
from aurora.pipeline import StageContext


def test_github_pages_delivery_writes_astro_content_post(tmp_path: Path) -> None:
    config = AuroraConfig()
    rendered = RenderedDigest(
        mode="unified_digest",
        title="Aurora Unified Digest",
        markdown="# Aurora Unified Digest\n\n## Research Papers\n\n1. [Paper](https://example.com) - 9.2/10",
        html="<html>email</html>",
        metadata={
            "item_counts": {"paper": 1, "repo": 0, "news": 0},
            "selected_item_ids": ["paper:one"],
            "featured_repo": "org/example",
            "featured_paper": "Useful Paper",
            "web_html": '<section class="aurora-section"><article class="aurora-card">Product UI</article></section>',
        },
    )
    context = StageContext(
        mode="unified_digest",
        run_id="run-20260526T033547Z",
        until=datetime(2026, 5, 26, 3, 35, 47, tzinfo=timezone.utc),
        config=config,
    )

    result = write_pages_artifact(
        rendered,
        context,
        GitHubPagesDeliveryConfig(publish_dir=tmp_path / "web" / "src" / "content" / "posts"),
    )

    post_path = tmp_path / "web" / "src" / "content" / "posts" / "2026-05-26-unified-digest.md"
    assert result.destination == str(post_path)
    assert result.metadata["astro_content"] is True
    assert result.metadata["content_dir"] == str(post_path.parent)

    post = post_path.read_text(encoding="utf-8")
    assert 'title: "Aurora Unified Digest"' in post
    assert 'author: "Aurora System"' in post
    assert 'digest_date: "2026-05-26"' in post
    assert 'featured_repo: "org/example"' in post
    assert 'featured_paper: "Useful Paper"' in post
    assert 'tags: ["digest", "aurora", "tech-news", "github", "research"]' in post
    assert "paper: 1" in post
    assert "Product UI" in post
    assert "aurora-card" in post
    assert "# Aurora Unified Digest" not in post
    assert "Generated by Aurora from run <code>run-20260526T033547Z</code>" in post


def test_github_pages_falls_back_to_markdown_when_web_html_absent(tmp_path: Path) -> None:
    context = StageContext(
        mode="tech_news",
        run_id="run-1",
        until=datetime(2026, 5, 25, 16, 0, tzinfo=timezone.utc),
        config=AuroraConfig(),
    )

    write_pages_artifact(
        RenderedDigest(
            mode="tech_news",
            title="Aurora Tech News",
            markdown="# Aurora Tech News\n\nSelected 2 tech news item(s).",
        ),
        context,
        GitHubPagesDeliveryConfig(publish_dir=tmp_path / "posts"),
    )

    post = (tmp_path / "posts" / "2026-05-26-tech-news.md").read_text(encoding="utf-8")
    assert "# Aurora Tech News" in post
    assert "Selected 2 tech news item(s)." in post
    assert 'tags: ["digest", "aurora", "tech-news"]' in post
